### PR TITLE
mp39339_wrongformat

### PR DESCRIPTION
**Pull request by derfred**
https://tickets.miceportal.de/browse/MP-39339

### CODE REVIEW

**Review by stereosupersonic — APPROVED** [review]
lgtm

**Comment by arthurbragaa** [comment]
LGTM

**Comment by stereosupersonic** [comment]
@arthurbragaa  we have to revert this. this change was the reason for the last weekends downtime

**Comment by arthurbragaa** [comment]
@stereosupersonic, I'm reverting right now

**Comment by arthurbragaa** [comment]
The pull request was reverted.
The pull request is now at: https://github.com/konvenit/CASino/pull/5

**Pull request merged**
