### PR TITLE
Rails7.0.3

### PR DESCRIPTION
**Pull request by anikolskiy**

### CODE REVIEW

**Review by dima4p — COMMENTED** [review]
Could you, please, remove me from this project?

**Review by Arsen7 — APPROVED** [review]

**Review by amin19948 — APPROVED** [review]

**Comment by dima4p** [comment]
> Could you, please, remove me from this project?

@anikolskiy , пожалуйста

**Comment by Arsen7** [comment]
@dima4p : Hi Dmitri! I'm sorry for that - I believe that this one is set as public, and possibly you may just set your notifications to "Ignore" using that [ Watch ] button above.
I have not found an option to remove you from here. :confused: 

P.S.: By the way, I think we have met on some ruby meetups in Munich several years ago! At least I saw that I have your phone number in my contacts. The world is small, isn't it? ;)

**Comment by dima4p** [comment]
Servus  Mariusz!

> @dima4p : Hi Dmitri! I'm sorry for that - I believe that this one is set as public, and possibly you may just set your notifications to "Ignore" using that [ Watch ] button above. I have not found an option to remove you from here. confused

Ah, OK. If it is the public project, no problem.
> 
> P.S.: By the way, I think we have met on some ruby meetups in Munich several years ago! At least I saw that I have your phone number in my contacts. The world is small, isn't it? ;)

Yes, exactly. Hope to see you on the next Rubyshift in November.

**Pull request merged**
